from_latest_tag = true
ignore_merge_commits = true
skip_ci = "[skip ci]"
skip_untracked = true
disable_changelog = false
disable_bump_commit = false
tag_prefix = ""

[changelog]
path = "CHANGELOG.md"
